### ISSUE TITLE
Add README.md, CONTRIBUTING.md and .editorconfig

### ISSUE THREAD

**Issue by ZombineDev** [savage309/HPC2015#2]
Привет! Курсът сe очертава да е интересен и се надявам да имам време да го посещавам ;) Междувременно, реших да разгледам материалите и ми хрумнаха няколко идеи за подобрения:
+ `README.md` - за какво е това repo и каква му е структурата. Освен това: в коя зала и от колко часа ще е следващата лекция.
+ `CONTRIBUTING.md` - инфо за това как някой може да помогне.
+ `.editorconfig` - See http://editorconfig.org. TL;DR, помага автоматизирано да се enforce-не code style.

**Comment by savage309** [comment]
Здрасти!
Благодарим за интереса и предложенията. Ще ги вземем предвид възможно най-скоро.
